# Generated by Django 4.2.13 on 2024-06-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=4100, verbose_name='Текст сообщения')),
                ('time', models.DateTimeField(verbose_name='Время напоминания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermodel', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Уведоиление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
