# Generated by Django 4.2.13 on 2024-06-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notesmodel',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='answer',
            field=models.TextField(blank=True, max_length=4100, null=True, verbose_name='Переменная для хранения нужной нам информации'),
        ),
    ]
