# Generated by Django 4.2.13 on 2024-06-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_notesmodel_options_usermodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='user',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID пользователя'),
        ),
    ]
